// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuJ9cjjN4tuFVUcnQLE3_C6ygRi7VnHxY',
    appId: '1:745238489327:web:69b4b8387ce39ca537d31a',
    messagingSenderId: '745238489327',
    projectId: 'chatapp-d204a',
    authDomain: 'chatapp-d204a.firebaseapp.com',
    storageBucket: 'chatapp-d204a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ye7HGjo_zcVC0T6Q3Qh0i6SPHMxvC7k',
    appId: '1:745238489327:android:9ea25f4ba734c3d337d31a',
    messagingSenderId: '745238489327',
    projectId: 'chatapp-d204a',
    storageBucket: 'chatapp-d204a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhow-OHjTAORBEjV0oYKmVeMyw02KfDY',
    appId: '1:745238489327:ios:31a0db02f56ad5e437d31a',
    messagingSenderId: '745238489327',
    projectId: 'chatapp-d204a',
    storageBucket: 'chatapp-d204a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRhow-OHjTAORBEjV0oYKmVeMyw02KfDY',
    appId: '1:745238489327:ios:31a0db02f56ad5e437d31a',
    messagingSenderId: '745238489327',
    projectId: 'chatapp-d204a',
    storageBucket: 'chatapp-d204a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuJ9cjjN4tuFVUcnQLE3_C6ygRi7VnHxY',
    appId: '1:745238489327:web:c12e5b7ba18d1d3f37d31a',
    messagingSenderId: '745238489327',
    projectId: 'chatapp-d204a',
    authDomain: 'chatapp-d204a.firebaseapp.com',
    storageBucket: 'chatapp-d204a.firebasestorage.app',
  );
}
